name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: deploy
        run: make deploy
      - name: pyspark
        channels:
          - conda-forge
        dependencies:
          - python=3.7.3
          - pytest=5.0.1
          - requests=2.22.0
          - pylint
          - pyspark=2.4.4